### ISSUE TITLE
rebuild error

### ISSUE THREAD

**Issue by qld-cf** [1111mp/electron_client#10]
`
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2
`

**Comment by 1111mp** [comment]
是的 应该是 `@journeyapps/sqlcipher` 这个库报错吧（在windows平台，它是一个别人配置好的sqlite的加密套件，也可以自己去配置），其实已经在本地把electron和其他所有依赖库都更新到最新版本了，但是很多api都变更了，然后发现自己的代码也需要重构，已经重写了部分，但是最近在忙着学习c++开发游戏引擎的部分，所以耽搁了，后续会继续迭代并且实现和完善IM的功能的。

**Comment by 1111mp** [comment]
作为 electron 学习参考的话，推荐一个非常成熟并且开源的项目：[Signal-Desktop](https://github.com/signalapp/Signal-Desktop)

**Comment by 1111mp** [comment]
已经重构了 Windows没有跑 目前MacOS没问题
