### ISSUE TITLE
请问 127.0.0.1:3000 端口这个服务器的代码在哪里？

### ISSUE THREAD

**Issue by carl-jin** [1111mp/electron_client#31]
首先感谢作者的开源，给了我们学习的机会。

想问下这个项目运行后，进入注册页面，然后提交表单后，请求发送给了 127.0.0.1:3000, 

但是我查看这个项目后，没有发现哪里在运行这个 3000 的服务器，请问这个是其他项目代码运行的服务器吗？

**Comment by 1111mp** [comment]
谢谢。
这是个前后端分离的项目，后台服务需要单独启动的：[im_server](https://github.com/1111mp/im_server)，nestjs开发的。
