### ISSUE TITLE
主进程直接调方法会提示未初始化

### ISSUE THREAD

**Issue by zmm2tysu** [1111mp/electron_client#45]
```
import sqlServer from '../db/server.ts'

sqlServer.getUsers()
```
会提示`Error: getInstance: globalInstance not set!`

难道这套架构只能从渲染进程通过ipc的方法来操作数据库吗？

**Comment by 1111mp** [comment]
可以从主进程直接调用的 但是数据库连接这些都是放在子进程中的 不管怎么样你都得保证数据库初始化建立连接了才能去调用

渲染进程调用其实也只是通过IPC通信到主进程 在主进程中去调用对应的方法的

**Comment by zmm2tysu** [comment]
我断点的时候发现是初始化后才调用的数据库操作，但是就是提示这个……

**Comment by zmm2tysu** [comment]
我是看的这个帖子https://juejin.cn/post/7202807471881306172#heading-1
然后只拷贝了db相关的代码

**Comment by zmm2tysu** [comment]
> ```
> import sqlServer from '../db/server.ts'
> 
> sqlServer.getUsers()
> ```
> 
> 会提示`Error: getInstance: globalInstance not set!`
> 
> 难道这套架构只能从渲染进程通过ipc的方法来操作数据库吗？

我这么写不会碰到什么可能闭包的情况，才导致globalInstance no set吧

**Comment by 1111mp** [comment]
你可以看看主进程的入口文件 [`src/mian/main.ts`](https://github.com/1111mp/electron_client/blob/master/src/main/main.ts) ，这个文件里面是入口 在 `app.whenReady()` 之后会去初始化 要是不太熟悉 你可以把项目代码拉下来 复制过去 看看有什么问题呢

**Comment by zmm2tysu** [comment]
[[electron-sqlite3-demo](https://github.com/zmm2tysu/electron-sqlite3-demo)](https://github.com/zmm2tysu/electron-sqlite3-demo.git)
我这边建了个最小的项目复现了这个问题，空了能帮忙看一看么

**Comment by zmm2tysu** [comment]
我是在ready后，初始化的db
![image](https://github.com/user-attachments/assets/5d5be728-c1fd-42b8-926c-e76d9b5b0932)

然后在mainWindow的ready-to-show事件中，延迟了3秒进行的数据库操作，然后就复现了这个错误

**Comment by zmm2tysu** [comment]
![image](https://github.com/user-attachments/assets/f59d38a5-b065-402d-9ec3-9eadb885117c)

**Comment by 1111mp** [comment]
看了一下你的代码 调用的时候应该使用 `sql.sqlCall('getUsers', [false])` 来调用 不是通过 `sqlServer.getUsers()` 直接调用 sqlServer相当于是直接在主进程环境中调用数据库的方法 你应该在主进程中通知子进程 然后让子进程去执行sql的方法

在 `sqlChannel.ts` 中的 initialize 方法 你可以改造一下
```ts
export function initialize(mainSQL: SQLType): void {
  if (initialized) {
    throw new Error('sqlChannels: already initialized!');
  }
  initialized = true;

  sql = mainSQL;

  ipcMain.handle(SQL_CHANNEL_KEY, async (_event, callName, ...args) => {
    if (!sql) {
      throw new Error(`${SQL_CHANNEL_KEY}: Not yet initialized!`);
    }
    return sql.sqlCall(callName, args);
  });
}

```

**Comment by zmm2tysu** [comment]
感谢答疑
