### ISSUE TITLE
可以整合下render+main的命令，一键启动

### ISSUE THREAD

**Issue by qld-cf** [1111mp/electron_client#9]
readme也可以更新下

**Comment by 1111mp** [comment]
你可以直接通过 `F5` 一键启动项目（Debug模式）。
package.json里面其实配了启动命令 `start`，但是主进程的启动是配置在webpack的devServer里面的，可以参考：
https://github.com/1111mp/electron_client/blob/24575a83a09106bfa9f3b84e1fac9d989a27994b/.erb/configs/webpack.config.renderer.dev.babel.js#L286
需要的话可以放开这个注释，直接通过 `npm run start` or `yarn start`启动
